# algorithms.mk: Lists of stemming modules.
#
# This file is generated by mkalgorithms.pl from a list of module names.
# Do not edit manually.

libstemmer_algorithms =\
    arabic\
    armenian\
    basque\
    catalan\
    danish\
    dutch\
    dutch_porter\
    english\
    esperanto\
    estonian\
    finnish\
    french\
    german\
    greek\
    hindi\
    hungarian\
    indonesian\
    irish\
    italian\
    lithuanian\
    nepali\
    norwegian\
    porter\
    portuguese\
    romanian\
    russian\
    serbian\
    spanish\
    swedish\
    tamil\
    turkish\
    yiddish

ISO_8859_1_algorithms =\
    basque\
    catalan\
    danish\
    dutch\
    dutch_porter\
    english\
    finnish\
    french\
    german\
    indonesian\
    irish\
    italian\
    norwegian\
    porter\
    portuguese\
    spanish\
    swedish

ISO_8859_2_algorithms =\
    hungarian

KOI8_R_algorithms =\
    russian
